= JBCNConf Website
// GitHub customization
ifdef::env-github[]
:toc: preamble
:badges:
:tag: master
:!toc-title:
:tip-caption: :bulb:
:note-caption: :paperclip:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This repository holds the public website for the link:http://www.jbcnconf.com/[JBCNConf], the Java conference is organized by the Barcelona JUG every summer.

== Building the website

The site is build with the link:https://jekyllrb.com/[Jekyll] and published with GitHub pages.
To run it you need to set up a basic Ruby (up to 2.7.x) environment.

For Linux and MacOS, the recommended way to install Ruby is with link:https://rvm.io/[RVM].
For Windows you can use link:https://rubyinstaller.org/[RubyInstaller] or the link:https://chocolatey.org/packages?q=ruby[chocolately package].

Once Ruby is installed, install the required gems with the following command.

 bundle install

=== Generated pages

IMPORTANT: Converting generated html is ONLY required when updating them.

Some pages use https://asciidoctor.org/[Asciidoctor] to generate the HTML.
`adoc` sources can be found under `tools` directory.

To convert them:

. Install Asciidoctor Ruby gem `gem install asciidoctor`
. Render each file with the `--no-header-footer` option (`-s` in short) specifying the source and target path.

Here is the list of the current generated files and their commands:

 $ asciidoctor tools/diversity.adoc -aidprefix -aidseparator=- -s -o 2019/_includes/diversity/diversity-terms.html
 $ asciidoctor tools/hackergarten.adoc -aidprefix -aidseparator=- -s -o 2019/_includes/hackergarten/hackergarten-content.html
 $ asciidoctor tools/talks-feedback.adoc -aidprefix -aidseparator=- -s -o 2019/_includes/feedback/feedback-talks-table.html
 $ asciidoctor tools/workshops-feedback.adoc -aidprefix -aidseparator=- -s -o 2019/_includes/feedback/feedback-workshops-table.html
 $ asciidoctor tools/become-sponsor.adoc -aidprefix -aidseparator=- -s -o 2020/_includes/sponsors/become-sponsor.html

[IMPORTANT]
====
Note that a real line break required two line-breaks, single ones are ignored.
Files are not converted automatically.
If changes in the sources are made, remember converting them and adding the generated html in the commit.
====

== Testing the website

=== Testing it locally (with Ruby installation)

Just fork the repo, open a shell, place yourself in the root and run
 
 $ bundle exec jekyll serve

of just

 $ jekyll serve

This will start a local embedded server on http://localhost:4000.
The server will stay up and self-update automatically.

=== Testing it locally (with Gradle)

If you have Gradle installed somewhere (or even have a project somewhere with the Gradle wrapper) you can
test without having anything installed. Just fork the repo, open a shell and run

 $ gradle -b jekyll.gradle -i
 
This will bootstrap everything into a throw-away folder and start up the local server on

 http://localhost:4000
 
The server will stay up and self-update automatically.

=== Testing it locally (with Docker)

Current Jekyll version used by https://pages.github.com/versions/[GitHub Pages] (v3.9.2) is not available at link:https://hub.docker.com/r/jekyll/jekyll/tags?page=1&name=3.[DockerHub].
Close available Jekyll images are 3.8 and 4.0.0, use at your own risk.

.docker run example
----
JEKYLL_VERSION="3.8" && docker run --rm \
--volume="$PWD:/srv/jekyll:Z" \
--publish 4000:4000 \
-it jekyll/jekyll:$JEKYLL_VERSION \
jekyll serve
----

=== Testing on a GitHub cloned repo

You can publish the site in your cloned repo to see the result of your changes.

First, enable GitHub pages in your forked repository and set it to publish to the gh-pages branch.

== Publication

Changes are published directly from `main` branch.
Make sure everything is correct before merging into it.

== Generating a new Edition

TBD

[IMPORTANT]
====
Remember to update the open graph values located at the `_layouts/default.html` page and replace the `<year>/assets/img/logos/og-image.png` image. They are used for the thumbnail generation at every social network.
====
