= JBCNConf Website
// GitHub customization
ifdef::env-github[]
:toc: preamble
:badges:
:tag: master
:!toc-title:
:tip-caption: :bulb:
:note-caption: :paperclip:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This repository holds the public website for the link:http://www.jbcnconf.com/[JBCNConf], the Java conference is organized by the Barcelona JUG every summer.

== Building the website

The site is build with the link:https://jekyllrb.com/[Jekyll] and published with GitHub pages.
To run it you need to setup a basic Ruby (up to 2.4.x) environment.

For Linux and MacOS, the recommended way to install Ruby is with link:https://rvm.io/[RVM].
For Windows you can use link:https://rubyinstaller.org/[RubyInstaller] or the link:https://chocolatey.org/packages?q=ruby[chocolately package].

Once Ruby is installed, install the required gems with the following command.

 bundler install

[IMPORTANT]
====
The required `ffi` gem is not yet fully supported in Ruby 2.5.x.
If you want to build the site with Ruby 2.5.x, skip `bundler` and install the gems manually with:

 gem install ffi --force -v 1.9.18
 gem install jekyll
====

== Testing the website

=== Testing it locally

Just fork the repo, open a shell, place yourself in the root and run

 $ jekyll serve

This will start a local embedded server on http://localhost:4000.
The server will stay up and self-update automatically.

=== Testing on a GitHub cloned repo

You can publish the site in your cloned repo to see the result of your changes.

First, enable GitHub pages in your fork and set it to publish to the gh-pages branch.
Then, build the site and commit the generated files under `_site` to the `gh-pages` branch.

[NOTE]
====
Automatic publishing won't work in cloned repos due to the use of a special token in the TravisCI configuration.
See https://github.com/jirutka/rake-jekyll#setup-for-github-pages-and-travis-ci for details.
====

== Publishing

=== Publishing the site

All changes to `master` are automatically published using a link:https://travis-ci.org/[TravisCI] build.

This means, the site will be updated when:

* changes are directly pushed into master.
* a branch is merged into master.
